# Generated by Django 4.1.7 on 2023-05-09 12:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('desription', models.TextField()),
                ('post_needed', models.CharField(max_length=250)),
                ('validation', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ensignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porfile_pic', models.ImageField(upload_to='profile_pics')),
                ('university', models.CharField(blank=True, max_length=300, null=True)),
                ('grade', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=300)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='themes_to_validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('specialite', models.CharField(choices=[('ACAD', 'ACAD'), ('ISIL', 'ISIL'), ('GTR', 'GTR'), ('IV', 'IV'), ('RSD', 'RSD'), ('HPC', 'HPC'), ('SSI', 'SSI'), ('SII', 'SII'), ('BIG DATA', 'BIG DATA'), ('BIOINFO', 'BIOINFO'), ('IL', 'IL')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='validated_themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('specialite', models.CharField(choices=[('ACAD', 'ACAD'), ('ISIL', 'ISIL'), ('GTR', 'GTR'), ('IV', 'IV'), ('RSD', 'RSD'), ('HPC', 'HPC'), ('SSI', 'SSI'), ('SII', 'SII'), ('BIG DATA', 'BIG DATA'), ('BIOINFO', 'BIOINFO'), ('IL', 'IL')], max_length=200)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porfile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('university', models.CharField(blank=True, max_length=300, null=True)),
                ('speciality', models.CharField(max_length=300)),
                ('interested', models.CharField(max_length=400)),
                ('CV', models.FileField(blank=True, max_length=1999999, null=True, upload_to='CVs')),
                ('study_level', models.CharField(choices=[('L3', 'L3'), ('M2', 'M2')], max_length=30)),
                ('github_link', models.URLField(blank=True, max_length=300)),
                ('linkedin_link', models.URLField(blank=True, max_length=300)),
                ('Role', models.CharField(choices=[('Binome', 'Binome'), ('monome', 'monome'), ('None', 'None')], default='None', max_length=20)),
                ('binome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binome', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pourcentage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='resp_epcialit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, choices=[('ACAD', 'ACAD'), ('ISIL', 'ISIL'), ('GTR', 'GTR'), ('IV', 'IV'), ('RSD', 'RSD'), ('HPC', 'HPC'), ('SSI', 'SSI'), ('SII', 'SII'), ('BIG DATA', 'BIG DATA'), ('BIOINFO', 'BIOINFO'), ('IL', 'IL')], max_length=200, null=True)),
                ('ensignant_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.ensignant')),
            ],
        ),
        migrations.CreateModel(
            name='pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=300)),
                ('description_text', models.TextField()),
                ('type', models.CharField(choices=[('question', 'question'), ('theme', 'theme')], max_length=30)),
                ('keywords', models.CharField(max_length=400)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('decription', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(choices=[('notification_binome', 'notification_binome'), ('notification_ensignant', 'notification_ensignant'), ('notification_responsable', 'notification_responsable')], max_length=100)),
                ('id_pub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.pub')),
                ('send_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('themes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pub')),
            ],
        ),
        migrations.CreateModel(
            name='jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_nd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_jury2', to='API.ensignant')),
                ('m_jury_st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_jury1', to='API.ensignant')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='API.ensignant')),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='API.validated_themes')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pub')),
            ],
        ),
        migrations.CreateModel(
            name='comission_validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensignant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_comission1', to='API.ensignant')),
                ('ensignant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_comission2', to='API.ensignant')),
                ('ensignant3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_comission3', to='API.ensignant')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.themes_to_validate')),
            ],
        ),
    ]
