# Generated by Django 4.1.7 on 2023-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_ensignant_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensignant',
            name='a_propos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
