# Generated by Django 4.1.7 on 2023-05-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_ensignant_a_propos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='type',
            field=models.CharField(choices=[('question', 'question'), ('theme', 'theme')], default='theme', max_length=30),
        ),
    ]
