# Generated by Django 4.1.7 on 2023-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_skill_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensignant',
            name='porfile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='porfile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
