# Generated by Django 4.1.7 on 2023-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_ensignant_porfile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='a_propos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
