# Generated by Django 4.1.7 on 2023-05-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_student_a_propos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comission_validation',
            name='ensignant3',
        ),
        migrations.RemoveField(
            model_name='comission_validation',
            name='theme',
        ),
        migrations.AddField(
            model_name='themes_to_validate',
            name='commission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.comission_validation'),
        ),
    ]
