# Generated by Django 4.1.7 on 2023-05-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_remove_comission_validation_ensignant3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes_to_validate',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.comission_validation'),
        ),
    ]
