# Generated by Django 4.1.7 on 2023-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_themes_to_validate_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes_to_validate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
