# Generated by Django 4.1.7 on 2023-05-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_themes_to_validate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes_to_validate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
