# Generated by Django 4.1.7 on 2023-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_themes_to_validate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes_to_validate',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L3', 'L3'), ('M2', 'M2')], max_length=200),
        ),
    ]
