# Generated by Django 4.1.7 on 2023-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_themes_to_validate_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='etat_avancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
