# Generated by Django 4.1.7 on 2023-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_etat_avancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='validated_themes',
            name='note1',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validated_themes',
            name='note2',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validated_themes',
            name='note3',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
