# Generated by Django 4.1.7 on 2023-05-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_validated_themes_moy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validated_themes',
            name='note1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validated_themes',
            name='note2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validated_themes',
            name='note3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
